ovs_mac_learn.c: check fgets() return value in ovsmac_scan_br()
Ignoring the return value from fgets() while skipping the first line
output by ovs-appctl causes compiler warnings when _FORTIFY_SOURCE is
defined.

  | src/lib/ovs_mac_learn/src/ovs_mac_learn.c: In function 'ovsmac_scan_br':
  | src/lib/ovs_mac_learn/src/ovs_mac_learn.c:253:5: error: ignoring return value of 'fgets', declared with attribute warn_unused_result [-Werror=unused-result]
  |      fgets(buf, sizeof(buf), ovs_appctl);
  |      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  | cc1: all warnings being treated as errors

Signed-off-by: Andre McCurdy <armccurdy@gmail.com>