osa: avoid possible truncated result from snprintf() in os_nif_linux.c
The os_nif_dhcpc_start() function in os_nif_linux.c may cause
snprintf to return a truncated result due to being passed an output
buffer which is too small to safely hold the maximal length result.

The following warnings were generated by gcc 9:

 | src/lib/osa/src/os_nif_linux.c: In function 'os_nif_dhcpc_start':
 | src/lib/osa/src/os_nif_linux.c:775:57: error: '%s' directive output may be truncated writing up to 299 bytes into a region of size 240 [-Werror=format-truncation=]
 |   775 |     snprintf(pidfile, sizeof(pidfile), "/var/run/udhcpc-%s.pid", pidname);
 |       |                                                         ^~
 | In file included from /.../recipe-sysroot/usr/include/stdio.h:873,
 |                  from src/lib/common/inc/os.h:31,
 |                  from src/lib/osa/src/os_nif_linux.c:40:
 | /.../recipe-sysroot/usr/include/bits/stdio2.h:67:10: note: '__builtin___snprintf_chk' output between 21 and 320 bytes into a destination of size 256

Fix the warning by using a more appropriate sized buffer for the
interface name.

Also tidy up the code a little by avoiding unnecessary duplicate
calls to app_build_profile_get() + app_build_number_get(), by
avoiding an unnecessary local buffer for udhcpc_s_option and by
using more consistent variable naming in os_nif_dhcpc_start() and
os_nif_dhcpc_stop().

Signed-off-by: Andre McCurdy <armccurdy@gmail.com>