wm2_radio.c: avoid possibility of truncated results from snprintf
Various functions in wm2_radio.c may cause snprintf to return a
truncated result due to being passed an output buffer which is too
small to safely hold the maximal length result.

The following warnings were generated by gcc 7:

 | src/wm2/src/wm2_radio.c: In function 'wm2_radio_config_update_cb':
 | src/wm2/src/wm2_radio.c:205:59: error: '%s' directive output may be truncated writing up to 128 bytes into a region of size 38 [-Werror=format-truncation=]
 |      snprintf(msg, sizeof(msg), "Updating ovsdb radio conf %s", rconf->if_name);
 |                                                            ^~
 | src/wm2/src/wm2_radio.c:205:5: note: 'snprintf' output between 27 and 155 bytes into a destination of size 64
 |      snprintf(msg, sizeof(msg), "Updating ovsdb radio conf %s", rconf->if_name);
 |      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 | src/wm2/src/wm2_radio.c: In function 'wm2_vif_config_update_cb':
 | src/wm2/src/wm2_radio.c:594:51: error: '%s' directive output may be truncated writing up to 128 bytes into a region of size 46 [-Werror=format-truncation=]
 |      snprintf(msg, sizeof(msg), "Updating VIF conf %s", vconf->if_name);
 |                                                    ^~
 | src/wm2/src/wm2_radio.c:594:5: note: 'snprintf' output between 19 and 147 bytes into a destination of size 64
 |      snprintf(msg, sizeof(msg), "Updating VIF conf %s", vconf->if_name);
 |      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 | src/wm2/src/wm2_radio.c: In function 'wm2_radio_vif_state_update_cb':
 | src/wm2/src/wm2_radio.c:667:52: error: '%s' directive output may be truncated writing up to 128 bytes into a region of size 45 [-Werror=format-truncation=]
 |      snprintf(msg, sizeof(msg), "Updating VIF state %s", vstate->if_name);
 |                                                     ^~
 | src/wm2/src/wm2_radio.c:667:5: note: 'snprintf' output between 20 and 148 bytes into a destination of size 64
 |      snprintf(msg, sizeof(msg), "Updating VIF state %s", vstate->if_name);
 |      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 | src/wm2/src/wm2_radio.c: In function 'wm2_radio_state_update_cb':
 | src/wm2/src/wm2_radio.c:171:54: error: '%s' directive output may be truncated writing up to 128 bytes into a region of size 43 [-Werror=format-truncation=]
 |      snprintf(msg, sizeof(msg), "Updating radio state %s", rstate->if_name);
 |                                                       ^~
 | src/wm2/src/wm2_radio.c:171:5: note: 'snprintf' output between 22 and 150 bytes into a destination of size 64
 |      snprintf(msg, sizeof(msg), "Updating radio state %s", rstate->if_name);
 |      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Signed-off-by: Andre McCurdy <armccurdy@gmail.com>