nm2_ovsdb.c: avoid possibility of truncated results from snprintf
Various functions in nm2_ovsdb.c may cause snprintf to return a
truncated result due to being passed an output buffer which is too
small to safely hold the maximal length result.

The following warnings were generated by gcc 7:

 | src/nm2/src/nm2_ovsdb.c: In function 'nm2_inet_state_update_cb':
 | src/nm2/src/nm2_ovsdb.c:85:59: error: '%s' directive output may be truncated writing up to 128 bytes into a region of size 38 [-Werror=format-truncation=]
 |      snprintf(msg, sizeof(msg), "Updating ovsdb inet state %s", istate->if_name);
 |                                                            ^~
 | src/nm2/src/nm2_ovsdb.c:85:5: note: 'snprintf' output between 27 and 155 bytes into a destination of size 64
 |      snprintf(msg, sizeof(msg), "Updating ovsdb inet state %s", istate->if_name);
 |      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 | src/nm2/src/nm2_ovsdb.c: In function 'nm2_inet_config_update_cb':
 | src/nm2/src/nm2_ovsdb.c:107:60: error: '%s' directive output may be truncated writing up to 128 bytes into a region of size 37 [-Werror=format-truncation=]
 |      snprintf(msg, sizeof(msg), "Updating ovsdb inet config %s", iconf->if_name);
 |                                                             ^~
 | src/nm2/src/nm2_ovsdb.c:107:5: note: 'snprintf' output between 28 and 156 bytes into a destination of size 64
 |      snprintf(msg, sizeof(msg), "Updating ovsdb inet config %s", iconf->if_name);
 |      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Signed-off-by: Andre McCurdy <armccurdy@gmail.com>