os_nif_linux.c: avoid possibility of truncated results from snprintf
os_nif_dhcpc_start() in os_nif_linux.c may cause snprintf to return a
truncated result due to being passed an output buffer which is too
small to safely hold the maximal length result when setting up the
value of hostname.

The following warnings were generated by gcc 8:

 | src/lib/osa/src/os_nif_linux.c: In function 'os_nif_dhcpc_start':
 | src/lib/osa/src/os_nif_linux.c:732:56: error: '%s' directive output may be truncated writing up to 255 bytes into a region of size 247 [-Werror=format-truncation=]
 |          snprintf(hostname, sizeof(hostname), "hostname:%s_Pod_%s", serial_num, sku_num);
 |                                                         ^~          ~~~~~~~~~~
 | src/lib/osa/src/os_nif_linux.c:732:9: note: 'snprintf' output between 15 and 525 bytes into a destination of size 256
 |          snprintf(hostname, sizeof(hostname), "hostname:%s_Pod_%s", serial_num, sku_num);
 |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 | src/lib/osa/src/os_nif_linux.c:728:56: error: '%s' directive output may be truncated writing up to 255 bytes into a region of size 247 [-Werror=format-truncation=]
 |          snprintf(hostname, sizeof(hostname), "hostname:%s_Pod", serial_num);
 |                                                         ^~       ~~~~~~~~~~
 | src/lib/osa/src/os_nif_linux.c:728:9: note: 'snprintf' output between 14 and 269 bytes into a destination of size 256
 |          snprintf(hostname, sizeof(hostname), "hostname:%s_Pod", serial_num);
 |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Signed-off-by: Andre McCurdy <armccurdy@gmail.com>